import type { ApiKeyRecord, AuditEventRecord, EnvironmentRecord, OrganizationMembershipRecord, OrganizationRecord, ProjectRecord, ProjectRuntimeBindingRecord, ProvisioningAttemptRecord, ProvisioningTaskRecord, RegionRecord, UserRecord } from '../types';
export declare function toUserResponse(record: UserRecord): {
    id: string;
    email: string;
    name: string;
    status: string;
    lastLoginAt: string | null;
    createdAt: string;
    updatedAt: string;
};
export declare function toMembershipResponse(record: OrganizationMembershipRecord): {
    id: string;
    organizationId: string;
    userId: string;
    role: "owner" | "admin" | "member";
    status: string;
};
export declare function toOrganizationResponse(record: OrganizationRecord): {
    id: string;
    name: string;
    slug: string;
    status: string;
    createdAt: string;
    updatedAt: string;
};
export declare function toRegionResponse(record: RegionRecord): {
    id: string;
    code: string;
    name: string;
    marketScope: string;
    deploymentTarget: string;
    isActive: boolean;
    metadata: Record<string, unknown>;
    createdAt: string;
    updatedAt: string;
};
export declare function toProjectResponse(record: ProjectRecord, organization: ReturnType<typeof toOrganizationResponse> | null): {
    id: string;
    name: string;
    slug: string;
    status: "provisioning" | "ready" | "error" | "paused";
    region: string;
    description: string;
    organizationId: string;
    organization: {
        id: string;
        name: string;
        slug: string;
        status: string;
        createdAt: string;
        updatedAt: string;
    } | null;
    createdAt: string;
    updatedAt: string;
};
export declare function toEnvironmentResponse(record: EnvironmentRecord): {
    id: string;
    projectId: string;
    name: string;
    slug: string;
    status: string;
    region: string;
    deploymentTarget: string;
    createdAt: string;
    updatedAt: string;
};
export declare function toApiKeyResponse(record: ApiKeyRecord): {
    id: string;
    projectId: string | null;
    organizationId: string | null;
    name: string;
    prefix: string;
    status: string;
    revokedAt: string | null;
    lastUsedAt: string | null;
    createdAt: string;
    updatedAt: string;
};
export declare function toProvisioningTaskResponse(record: ProvisioningTaskRecord, region: ReturnType<typeof toRegionResponse> | null): {
    id: string;
    projectId: string;
    environmentId: string | null;
    region: {
        id: string;
        code: string;
        name: string;
        marketScope: string;
        deploymentTarget: string;
        isActive: boolean;
        metadata: Record<string, unknown>;
        createdAt: string;
        updatedAt: string;
    } | null;
    status: "ready" | "failed" | "requested" | "queued" | "running" | "retrying";
    source: string;
    requestedByUserId: string | null;
    currentAttempt: number;
    maxAttempts: number;
    lastError: string | null;
    diagnostics: Record<string, unknown>;
    createdAt: string;
    updatedAt: string;
    startedAt: string | null;
    completedAt: string | null;
    nextRunAt: string;
    claimedBy: string | null;
    claimedAt: string | null;
    claimExpiresAt: string | null;
    lastHeartbeatAt: string | null;
    lastTransitionAt: string;
};
export declare function toProvisioningAttemptResponse(record: ProvisioningAttemptRecord): {
    id: string;
    taskId: string;
    attemptNo: number;
    status: string;
    adapter: string;
    step: string | null;
    errorMessage: string | null;
    diagnostics: Record<string, unknown>;
    createdAt: string;
    startedAt: string | null;
    completedAt: string | null;
    nextRunAt: string;
    claimedBy: string | null;
    claimedAt: string | null;
    claimExpiresAt: string | null;
    lastHeartbeatAt: string | null;
    lastTransitionAt: string;
};
export declare function toRuntimeBindingResponse(record: ProjectRuntimeBindingRecord): {
    id: string;
    projectId: string;
    regionId: string | null;
    databaseRef: string | null;
    storageRef: string | null;
    authNamespaceRef: string | null;
    functionsNamespaceRef: string | null;
    status: string;
    diagnostics: Record<string, unknown>;
    createdAt: string;
    updatedAt: string;
};
export declare function toAuditResponse(record: AuditEventRecord): {
    id: string;
    organizationId: string | null;
    projectId: string | null;
    actorUserId: string | null;
    action: string;
    targetType: string;
    targetId: string | null;
    metadata: Record<string, unknown>;
    createdAt: string;
};
