import { randomUUID } from 'node:crypto'

export interface SkillPack {
  name: string
  title: string
  description: string
  skillMd: string
  references?: { path: string; content: string }[]
  metadata: Record<string, unknown>
}

export interface GenerateResult {
  id: string
  object: string
  source: {
    type: 'github_profile' | 'github_repo' | 'docs' | 'text'
    username?: string
    repoUrl?: string
    url?: string
    name?: string
  }
  skill: SkillPack
  exports: {
    cursor?: { files: { path: string; content: string }[] }
    claude?: { files: { path: string; content: string }[] }
  }
}

function generateId(): string {
  return 'skill_req_' + randomUUID().slice(0, 12)
}

function now(): string {
  return new Date().toISOString()
}

function buildSkillMd(
  name: string,
  title: string,
  description: string,
  sections: string[],
  generator: string,
): string {
  return `# ${title}

## Purpose
${description}

## When to Use
This skill was auto-generated by Talocode Skills API (${generator}). Use it when working on or with the described project/profile.

${sections.join('\n\n')}

## References
This skill was generated programmatically. Verify accuracy before relying on it in critical contexts.
`
}

function buildProfileSections(username: string, profile: Record<string, unknown>): string[] {
  const sections: string[] = []
  sections.push(`## Project Context\nThis skill represents the GitHub profile of **${username}**.`)
  if (profile.bio) {
    sections.push(`## Profile Bio\n${profile.bio}`)
  }
  if (profile.company) {
    sections.push(`## Organization\n${profile.company}`)
  }
  if (profile.location) {
    sections.push(`## Location\n${profile.location}`)
  }
  if (profile.blog) {
    sections.push(`## Links\n- Blog: ${profile.blog}`)
  }
  if (Array.isArray(profile.repos) && profile.repos.length > 0) {
    const repoList = (profile.repos as { name: string; description?: string; language?: string }[])
      .map((r) => `- **${r.name}**${r.language ? ` (${r.language})` : ''}${r.description ? `: ${r.description}` : ''}`)
      .join('\n')
    sections.push(`## Repositories\n${repoList}`)
  }
  sections.push(`## Coding Rules\n- Follow the patterns and conventions used in ${username}'s repositories.\n- Respect existing project structures.\n- Use appropriate languages and frameworks as detected from repos.`)
  sections.push(`## Output Style\n- Match the coding style observed in the profile's public repositories.\n- Follow community best practices for the detected languages.`)
  return sections
}

function buildRepoSections(repoUrl: string, repoData: Record<string, unknown>): string[] {
  const sections: string[] = []
  sections.push(`## Project Context\nThis skill was generated from the repository at **${repoUrl}**.`)
  if (repoData.description) {
    sections.push(`## Description\n${repoData.description}`)
  }
  if (repoData.language) {
    sections.push(`## Primary Language\n${repoData.language}`)
  }
  if (repoData.topics) {
    sections.push(`## Topics\n${(repoData.topics as string[]).join(', ')}`)
  }
  if (repoData.readme) {
    sections.push(`## Project Overview\n${(repoData.readme as string).slice(0, 2000)}`)
  }
  sections.push(`## Architecture\nRefer to the repository structure and key files for architecture decisions.`)
  sections.push(`## Commands\nRefer to the repository's package.json, Makefile, or scripts directory for available commands.`)
  sections.push(`## Coding Rules\n- Follow the coding standards established in this repository.\n- Maintain consistency with existing patterns.\n- Respect the project's architectural decisions.`)
  sections.push(`## Output Style\n- Match the code style, naming conventions, and patterns used in the repository.`)
  return sections
}

function buildDocsSections(url: string, content: string): string[] {
  const sections: string[] = []
  sections.push(`## Source\nThis skill was generated from documentation at **${url}**.`)
  const cleaned = content
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
    .replace(/<[^>]+>/g, '')
  sections.push(`## Documentation Content\n${cleaned.slice(0, 3000)}`)
  sections.push(`## API Patterns\nFollow the API patterns and conventions documented at the source URL.`)
  sections.push(`## Integration Steps\nRefer to the documentation for setup, configuration, and usage instructions.`)
  return sections
}

function buildTextSections(name: string, content: string, focus?: string[]): string[] {
  const sections: string[] = []
  sections.push(`## Context\nThis skill was generated from provided text for **${name}**.`)
  if (content.length > 0) {
    sections.push(`## Content\n${content.slice(0, 3000)}`)
  }
  if (focus && focus.length > 0) {
    sections.push(`## Focus Areas\n- ${focus.join('\n- ')}`)
  }
  sections.push(`## Rules\n- Follow the patterns and conventions described in the provided context.\n- Maintain consistency with the described approach.`)
  return sections
}

function buildCursorExport(skillMd: string): { files: { path: string; content: string }[] } {
  return {
    files: [
      { path: 'SKILL.md', content: skillMd },
      { path: '.cursorrules', content: skillMd },
    ],
  }
}

function buildClaudeExport(skillMd: string): { files: { path: string; content: string }[] } {
  return {
    files: [
      { path: 'SKILL.md', content: skillMd },
      { path: 'CLAUDE.md', content: skillMd },
    ],
  }
}

export async function generateFromProfile(input: {
  username: string
  target: string
  focus?: string[]
  includeRepositories?: boolean
  maxRepositories?: number
}): Promise<GenerateResult> {
  const focus = input.focus ?? ['coding_style', 'project_patterns']

  let profile: Record<string, unknown> = { username: input.username }

  try {
    const token = typeof process !== 'undefined' ? process.env.GITHUB_TOKEN : undefined
    const headers: Record<string, string> = {
      Accept: 'application/vnd.github.v3+json',
      'User-Agent': 'talocode-skills-api-v0.1',
    }
    if (token) headers.Authorization = `Bearer ${token}`

    const userRes = await fetch(`https://api.github.com/users/${input.username}`, { headers, signal: AbortSignal.timeout(10000) })
    if (userRes.ok) {
      const userData = await userRes.json() as Record<string, unknown>
      profile = { ...profile, ...userData }
    }

    if (input.includeRepositories) {
      const maxRepos = input.maxRepositories ?? 8
      const reposRes = await fetch(
        `https://api.github.com/users/${input.username}/repos?per_page=${maxRepos}&sort=updated&direction=desc`,
        { headers, signal: AbortSignal.timeout(10000) },
      )
      if (reposRes.ok) {
        const reposData = await reposRes.json() as Record<string, unknown>[]
        profile.repos = reposData.map((r) => ({
          name: r.name,
          description: r.description,
          language: r.language,
          stars: r.stargazers_count,
          forks: r.forks_count,
        }))
      }
    }
  } catch {
    profile.generation_note = 'GitHub API fetch failed; using minimal profile data'
  }

  const name = `${input.username.toLowerCase()}-github-profile`
  const title = `${input.username} GitHub Profile Skill`
  const description = `Skill pack generated from ${input.username}'s GitHub profile. ${focus.length > 0 ? `Focus: ${focus.join(', ')}.` : ''}`
  const sections = buildProfileSections(input.username, profile)
  const generatorInfo = process.env.TALOCODE_SKILLS_PROVIDER ? 'provider-assisted' : 'deterministic'
  const skillMd = buildSkillMd(name, title, description, sections, generatorInfo)

  const skill: SkillPack = {
    name,
    title,
    description,
    skillMd,
    references: [
      { path: 'references/source-summary.md', content: `GitHub profile: ${input.username}\nGenerated: ${now()}\nGenerator: ${generatorInfo}` },
    ],
    metadata: {
      sourceType: 'github_profile',
      username: input.username,
      target: input.target,
      focus,
      generatedAt: now(),
      generator: `talocode-skills-api-v0.1-${generatorInfo}`,
    },
  }

  const exports: GenerateResult['exports'] = {}
  if (input.target === 'cursor' || input.target === 'opencode') {
    exports.cursor = buildCursorExport(skillMd)
  }
  if (input.target === 'claude' || input.target === 'codra') {
    exports.claude = buildClaudeExport(skillMd)
  }

  return {
    id: generateId(),
    object: 'skills.generated',
    source: { type: 'github_profile', username: input.username },
    skill,
    exports,
  }
}

export async function generateFromRepo(input: {
  repoUrl: string
  target: string
  focus?: string[]
}): Promise<GenerateResult> {
  const focus = input.focus ?? ['architecture', 'commands', 'coding_rules']

  let repoData: Record<string, unknown> = {}

  try {
    const parsed = new URL(input.repoUrl)
    const parts = parsed.pathname.replace(/^\//, '').replace(/\.git$/, '').split('/')
    const owner = parts[0]
    const repo = parts[1]

    if (owner && repo) {
      const token = typeof process !== 'undefined' ? process.env.GITHUB_TOKEN : undefined
      const headers: Record<string, string> = {
        Accept: 'application/vnd.github.v3+json',
        'User-Agent': 'talocode-skills-api-v0.1',
      }
      if (token) headers.Authorization = `Bearer ${token}`

      const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers, signal: AbortSignal.timeout(10000) })
      if (repoRes.ok) {
        const data = await repoRes.json() as Record<string, unknown>
        repoData = {
          name: data.name,
          full_name: data.full_name,
          description: data.description,
          language: data.language,
          topics: data.topics,
          stars: data.stargazers_count,
          forks: data.forks_count,
          default_branch: data.default_branch,
        }
      }

      const readmeRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/readme`, {
        headers: { ...headers, Accept: 'application/vnd.github.v3.raw' },
        signal: AbortSignal.timeout(10000),
      })
      if (readmeRes.ok) {
        repoData.readme = await readmeRes.text()
      }
    }
  } catch {
    repoData.generation_note = 'GitHub API fetch failed; using minimal repo data'
  }

  const name = `repo-${(repoData.name as string) || 'unknown'}`.toLowerCase().replace(/[^a-z0-9-]/g, '-')
  const title = `${(repoData.full_name as string) || input.repoUrl} Skill`
  const description = `Skill pack generated from repository ${input.repoUrl}. ${focus.length > 0 ? `Focus: ${focus.join(', ')}.` : ''}`
  const sections = buildRepoSections(input.repoUrl, repoData)
  const generatorInfo = process.env.TALOCODE_SKILLS_PROVIDER ? 'provider-assisted' : 'deterministic'
  const skillMd = buildSkillMd(name, title, description, sections, generatorInfo)

  const skill: SkillPack = {
    name,
    title,
    description,
    skillMd,
    references: [
      { path: 'references/source-summary.md', content: `Repository: ${input.repoUrl}\nGenerated: ${now()}\nGenerator: ${generatorInfo}` },
    ],
    metadata: {
      sourceType: 'github_repo',
      repoUrl: input.repoUrl,
      target: input.target,
      focus,
      generatedAt: now(),
      generator: `talocode-skills-api-v0.1-${generatorInfo}`,
    },
  }

  const exports: GenerateResult['exports'] = {}
  if (input.target === 'cursor' || input.target === 'opencode') {
    exports.cursor = buildCursorExport(skillMd)
  }
  if (input.target === 'claude' || input.target === 'codra') {
    exports.claude = buildClaudeExport(skillMd)
  }

  return {
    id: generateId(),
    object: 'skills.generated',
    source: { type: 'github_repo', repoUrl: input.repoUrl },
    skill,
    exports,
  }
}

export async function generateFromDocs(input: {
  url: string
  target: string
  focus?: string[]
}): Promise<GenerateResult> {
  const parsed = new URL(input.url)
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('Only http and https URLs are supported.')
  }
  const hostname = parsed.hostname.toLowerCase()
  if (hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '0.0.0.0' || hostname.startsWith('10.') || hostname.startsWith('172.16.') || hostname.startsWith('192.168.')) {
    throw new Error('URLs pointing to private IPs or localhost are not allowed.')
  }

  let content = ''
  try {
    const res = await fetch(input.url, { signal: AbortSignal.timeout(15000) })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const raw = await res.text()
    content = raw.slice(0, 50000)
  } catch (error) {
    throw new Error(`Failed to fetch docs URL: ${error instanceof Error ? error.message : 'unknown error'}`)
  }

  const focus = input.focus ?? ['api_usage', 'integration_steps']
  const name = `docs-${hostname.replace(/[^a-z0-9]/g, '-')}`
  const title = `${hostname} Documentation Skill`
  const description = `Skill pack generated from documentation at ${input.url}.`
  const sections = buildDocsSections(input.url, content)
  const generatorInfo = process.env.TALOCODE_SKILLS_PROVIDER ? 'provider-assisted' : 'deterministic'
  const skillMd = buildSkillMd(name, title, description, sections, generatorInfo)

  const skill: SkillPack = {
    name,
    title,
    description,
    skillMd,
    references: [
      { path: 'references/source-summary.md', content: `Documentation URL: ${input.url}\nFetched: ${now()}\nContent length: ${content.length}\nGenerator: ${generatorInfo}` },
    ],
    metadata: {
      sourceType: 'docs',
      url: input.url,
      target: input.target,
      focus,
      generatedAt: now(),
      generator: `talocode-skills-api-v0.1-${generatorInfo}`,
    },
  }

  const exports: GenerateResult['exports'] = {}
  if (input.target === 'cursor' || input.target === 'opencode') {
    exports.cursor = buildCursorExport(skillMd)
  }
  if (input.target === 'claude' || input.target === 'codra') {
    exports.claude = buildClaudeExport(skillMd)
  }

  return {
    id: generateId(),
    object: 'skills.generated',
    source: { type: 'docs', url: input.url },
    skill,
    exports,
  }
}

export async function generateFromText(input: {
  name: string
  content: string
  target: string
  focus?: string[]
}): Promise<GenerateResult> {
  const focus = input.focus ?? ['api', 'sdk', 'patterns']
  const name = input.name.toLowerCase().replace(/[^a-z0-9-]/g, '-')
  const title = `${input.name} Skill`
  const description = `Skill pack generated from provided text for ${input.name}.`
  const sections = buildTextSections(input.name, input.content, focus)
  const generatorInfo = process.env.TALOCODE_SKILLS_PROVIDER ? 'provider-assisted' : 'deterministic'
  const skillMd = buildSkillMd(name, title, description, sections, generatorInfo)

  const skill: SkillPack = {
    name,
    title,
    description,
    skillMd,
    references: [
      { path: 'references/source-summary.md', content: `Source: ${input.name}\nGenerated: ${now()}\nContent length: ${input.content.length}\nGenerator: ${generatorInfo}` },
    ],
    metadata: {
      sourceType: 'text',
      sourceName: input.name,
      target: input.target,
      focus,
      generatedAt: now(),
      generator: `talocode-skills-api-v0.1-${generatorInfo}`,
    },
  }

  const exports: GenerateResult['exports'] = {}
  if (input.target === 'cursor' || input.target === 'opencode') {
    exports.cursor = buildCursorExport(skillMd)
  }
  if (input.target === 'claude' || input.target === 'codra') {
    exports.claude = buildClaudeExport(skillMd)
  }

  return {
    id: generateId(),
    object: 'skills.generated',
    source: { type: 'text', name: input.name },
    skill,
    exports,
  }
}

export function exportForCursor(skill: SkillPack): GenerateResult['exports'] {
  return { cursor: buildCursorExport(skill.skillMd) }
}

export function exportForClaude(skill: SkillPack): GenerateResult['exports'] {
  return { claude: buildClaudeExport(skill.skillMd) }
}
