import { createProductClient } from './product-client'
import { mapHttpStatusToMcpError, MCP_ERROR_CODES } from './errors'
import {
  teraWritingRewriteSchema,
  teraWritingDraftSchema,
  teraCodingExplainSchema,
  teraCodingReviewSchema,
  agentBrowserCheckSchema,
  agentBrowserScreenshotSchema,
  agentBrowserExtractSchema,
  agentBrowserAnalyzeSchema,
  agentBrowserTraceReportSchema,
  cliploopBriefGenerateSchema,
  cliploopScriptGenerateSchema,
  cliploopVideoRenderSchema,
  cliploopCampaignCreateSchema,
  cliploopCampaignPackageSchema,
  cloudPricingSchema,
  skillsGenerateProfileSchema,
  skillsGenerateRepoSchema,
  skillsGenerateDocsSchema,
  skillsGenerateTextSchema,
  skillsExportCursorSchema,
  skillsExportClaudeSchema,
  invoicelaneHealthSchema,
  invoicelanePricingSchema,
  invoicelaneCapabilitiesSchema,
  invoicelaneExtractSchema,
  invoicelaneExtractReceiptSchema,
  invoicelaneExtractInvoiceSchema,
  invoicelaneValidateSchema,
  invoicelaneExportCsvSchema,
  geolaneHealthSchema,
  geolanePricingSchema,
  geolaneCapabilitiesSchema,
  geolaneAuditSchema,
  geolaneCrawlersSchema,
  geolaneLlmsTxtSchema,
  geolaneCitationReadinessSchema,
  geolaneCompareSchema,
  webdatalaneFetchSchema,
  webdatalaneExtractSchema,
  webdatalaneMarkdownSchema,
  webdatalaneMetadataSchema,
  webdatalaneLinksSchema,
  webdatalaneStructuredSchema,
  webdatalaneCrawlPlanSchema,
  webdatalaneScreenshotSchema,
  crawlerlaneLogsIngestSchema,
  crawlerlaneBotsClassifySchema,
  crawlerlanePagesAnalyzeSchema,
  crawlerlane404AnalyzeSchema,
  crawlerlaneAiVisibilityScoreSchema,
  crawlerlaneReportGenerateSchema,
  crawlerlaneSitemapSuggestSchema,
  crawlerlaneRobotsAuditSchema,
  crawlerlaneExportMarkdownSchema,
  crawlerlaneExportJsonSchema,
  opensourcelaneRepoAnalyzeSchema,
  opensourcelaneAlternativesFindSchema,
  opensourcelaneMigrationPlanSchema,
  opensourcelaneCostEstimateSchema,
  opensourcelaneRiskScoreSchema,
  opensourcelaneBriefGenerateSchema,
  opensourcelaneToolsCompareSchema,
  opensourcelaneDeploymentPlanSchema,
  opensourcelaneLicenseAuditSchema,
  opensourcelaneExportMarkdownSchema,
  opensourcelaneExportJsonSchema,
  forgecadDesignGenerateSchema,
  forgecadOpenScadGenerateSchema,
  forgecadBomGenerateSchema,
  forgecadCutlistGenerateSchema,
  forgecadAssemblyPlanSchema,
  forgecadPrintabilityCheckSchema,
  forgecadManufacturabilityCheckSchema,
  forgecadDesignReviewSchema,
  forgecadMaterialEstimateSchema,
  forgecadToolsDetectSchema,
  forgecadRenderOpenScadSchema,
  forgecadExportMarkdownSchema,
  forgecadExportJsonSchema,
  signallaneXAnalyzeSchema,
  signallaneXContentPlanSchema,
  signallaneXPostDraftsSchema,
  signallaneXExperimentsSchema,
  signallaneXReportSchema,
  ugclaneStrategyGenerateSchema,
  ugclaneCompetitorAnalyzeSchema,
  ugclaneHooksGenerateSchema,
  ugclaneScriptsGenerateSchema,
  ugclaneAccountsPlanSchema,
  ugclaneCalendarGenerateSchema,
  ugclaneExperimentsGenerateSchema,
  ugclaneReportGenerateSchema,
  ugclaneExportMarkdownSchema,
  ugclaneExportJsonSchema,
  replylaneOpportunityScoreSchema,
  replylaneTargetsRankSchema,
  replylaneRepliesDraftSchema,
  replylaneRepliesRiskSchema,
  replylanePostsGrokCheckSchema,
  replylaneActivityAuditSchema,
  replylaneFeedsMigrateSchema,
  replylaneExportMarkdownSchema,
  replylaneExportJsonSchema,
  tradiaHealthSchema,
  tradiaAgentPlanSchema,
  tradiaMarketAnalyzeSchema,
  tradiaSignalEvaluateSchema,
  tradiaRiskCheckSchema,
  tradiaTradeProposeSchema,
  tradiaTradeJournalSchema,
  tradiaPortfolioReportSchema,
  tradiaPerformanceAnalyzeSchema,
  tradiaPublicUpdateGenerateSchema,
  tradiaBacktestSimulateSchema,
  tradiaAccountabilityCardSchema,
  tradiaExportMarkdownSchema,
  tradiaExportJsonSchema,
} from './schemas'
import type { McpToolDefinition, McpToolResult } from './types'

export interface ToolContext {
  apiKey: string
}

export async function callTool(
  tool: McpToolDefinition,
  args: Record<string, unknown> | undefined,
  ctx: ToolContext,
): Promise<McpToolResult> {
  const client = createProductClient(ctx.apiKey)

  const body = tool.method === 'POST' ? args : undefined
  console.error('DEBUG: tool=%s method=%s body=%s', tool.name, tool.method, JSON.stringify(body))
  const result = await client.request(tool.method, tool.route, body)

  if (!result.ok) {
    const mcpError = mapHttpStatusToMcpError(result.status, result.body)
    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify({ ok: false, error: mcpError.message, code: mcpError.code, data: mcpError.data ?? null }),
        },
      ],
      isError: true,
    }
  }

  return {
    content: [
      {
        type: 'text',
        text: JSON.stringify({ ok: true, data: result.body }),
      },
    ],
  }
}

export const ALL_TOOLS: McpToolDefinition[] = [
  {
    name: 'tera_writing_rewrite',
    description: 'Rewrite text with a specific style and tone using Tera. Provide text to rewrite and optional style/tone/maxLength parameters.',
    inputSchema: teraWritingRewriteSchema,
    route: '/v1/tera/writing/rewrite',
    method: 'POST',
    product: 'tera',
    action: 'writing.rewrite',
    estimatedCredits: 5,
  },
  {
    name: 'tera_writing_draft',
    description: 'Draft content (email, social post, announcement, article, doc) using Tera. Provide type and brief describing what to write.',
    inputSchema: teraWritingDraftSchema,
    route: '/v1/tera/writing/draft',
    method: 'POST',
    product: 'tera',
    action: 'writing.draft',
    estimatedCredits: 10,
  },
  {
    name: 'tera_coding_explain',
    description: 'Explain code at beginner, intermediate, or advanced level using Tera. Provide language and code snippet.',
    inputSchema: teraCodingExplainSchema,
    route: '/v1/tera/coding/explain',
    method: 'POST',
    product: 'tera',
    action: 'coding.explain',
    estimatedCredits: 10,
  },
  {
    name: 'tera_coding_review',
    description: 'Review code for issues, bugs, security, and performance using Tera. Provide language and code to review.',
    inputSchema: teraCodingReviewSchema,
    route: '/v1/tera/coding/review',
    method: 'POST',
    product: 'tera',
    action: 'coding.review',
    estimatedCredits: 20,
  },
  {
    name: 'agent_browser_check',
    description: 'Check a website URL for status, content, and optionally capture a screenshot or run vision analysis. Provide URL to check.',
    inputSchema: agentBrowserCheckSchema,
    route: '/v1/agent-browser/check',
    method: 'POST',
    product: 'agent_browser',
    action: 'browser.check',
    estimatedCredits: 5,
  },
  {
    name: 'agent_browser_screenshot',
    description: 'Capture a screenshot of a website URL. Optionally set fullPage, viewport width/height. Provide URL to screenshot.',
    inputSchema: agentBrowserScreenshotSchema,
    route: '/v1/agent-browser/screenshot',
    method: 'POST',
    product: 'agent_browser',
    action: 'browser.screenshot',
    estimatedCredits: 8,
  },
  {
    name: 'agent_browser_trace_report',
    description: 'Execute browser trace steps on a URL and report results. Provide URL and array of steps (click, type, navigate).',
    inputSchema: agentBrowserTraceReportSchema,
    route: '/v1/agent-browser/trace-report',
    method: 'POST',
    product: 'agent_browser',
    action: 'browser.trace_report',
    estimatedCredits: 15,
  },
  {
    name: 'agent_browser_extract',
    description: 'Extract structured content from a URL including title, description, headings, text, links, images, and metadata. Returns clean readable content without browser rendering.',
    inputSchema: agentBrowserExtractSchema,
    route: '/v1/agent-browser/extract',
    method: 'POST',
    product: 'agent_browser',
    action: 'browser.extract',
    estimatedCredits: 15,
  },
  {
    name: 'agent_browser_analyze',
    description: 'Analyze page content from a URL using AI. Returns summary, sentiment, entities, topics, and keywords extracted from the page text.',
    inputSchema: agentBrowserAnalyzeSchema,
    route: '/v1/agent-browser/analyze',
    method: 'POST',
    product: 'agent_browser',
    action: 'browser.analyze',
    estimatedCredits: 25,
  },
  {
    name: 'cliploop_brief_generate',
    description: 'Generate a video brief for short-form content. Provide a prompt describing the video concept and optional channel/tone/duration.',
    inputSchema: cliploopBriefGenerateSchema,
    route: '/v1/cliploop/brief/generate',
    method: 'POST',
    product: 'cliploop',
    action: 'brief.generate',
    estimatedCredits: 15,
  },
  {
    name: 'cliploop_script_generate',
    description: 'Generate a video script from a brief. Provide the briefId from brief generation.',
    inputSchema: cliploopScriptGenerateSchema,
    route: '/v1/cliploop/script/generate',
    method: 'POST',
    product: 'cliploop',
    action: 'script.generate',
    estimatedCredits: 15,
  },
  {
    name: 'cliploop_video_render',
    description: 'Render a video from a script. Provide the scriptId from script generation and optional format/quality.',
    inputSchema: cliploopVideoRenderSchema,
    route: '/v1/cliploop/video/render',
    method: 'POST',
    product: 'cliploop',
    action: 'video.render',
    estimatedCredits: 200,
  },
  {
    name: 'cliploop_campaign_create',
    description: 'Create a ClipLoop campaign. Provide name and platform.',
    inputSchema: cliploopCampaignCreateSchema,
    route: '/v1/cliploop/campaign/create',
    method: 'POST',
    product: 'cliploop',
    action: 'campaign.create',
    estimatedCredits: 50,
  },
  {
    name: 'cliploop_campaign_package',
    description: 'Package a ClipLoop campaign for delivery. Provide campaignId.',
    inputSchema: cliploopCampaignPackageSchema,
    route: '/v1/cliploop/campaign/package',
    method: 'POST',
    product: 'cliploop',
    action: 'campaign.package',
    estimatedCredits: 400,
  },
  {
    name: 'cloud_pricing',
    description: 'Get the full Talocode Cloud pricing catalog with all products, actions, and credit costs.',
    inputSchema: cloudPricingSchema,
    route: '/api/v1/cloud/pricing',
    method: 'GET',
    product: 'cloud',
    action: 'pricing.list',
    estimatedCredits: null,
  },
  {
    name: 'invoicelane_health',
    description:
      'Check InvoiceLane Document API health, version (v0.2), and available endpoints. Free (no credits).',
    inputSchema: invoicelaneHealthSchema,
    route: '/v1/invoicelane/health',
    method: 'GET',
    product: 'invoicelane',
    action: 'invoicelane.health',
    estimatedCredits: null,
  },
  {
    name: 'invoicelane_pricing',
    description:
      'Get InvoiceLane credit pricing: extract 20, receipt.extract 20, invoice.extract 30, validate 10, export.csv 5. Free (no credits).',
    inputSchema: invoicelanePricingSchema,
    route: '/v1/invoicelane/pricing',
    method: 'GET',
    product: 'invoicelane',
    action: 'invoicelane.pricing',
    estimatedCredits: null,
  },
  {
    name: 'invoicelane_capabilities',
    description:
      'List InvoiceLane capabilities, schema contract (invoice requires invoiceNumber/total/currency/date; receipt requires total/currency/date), endpoints, and limitations (text-only, no OCR/PDF in v0.2). Free (no credits).',
    inputSchema: invoicelaneCapabilitiesSchema,
    route: '/v1/invoicelane/capabilities',
    method: 'GET',
    product: 'invoicelane',
    action: 'invoicelane.capabilities',
    estimatedCredits: null,
  },
  {
    name: 'invoicelane_extract',
    description:
      'Schema-first extract from invoice/receipt text. Returns merchant/vendor, totals, line items, confidence, missingFields, totalsConsistent, warnings. Provide text (OCR/PDF not supported). 20 credits.',
    inputSchema: invoicelaneExtractSchema,
    route: '/v1/invoicelane/extract',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.extract',
    estimatedCredits: 20,
  },
  {
    name: 'invoicelane_extract_receipt',
    description:
      'Extract a receipt as structured JSON (receiptNumber, vendor, total, date, missingFields, totalsConsistent). Provide raw receipt text. 20 credits.',
    inputSchema: invoicelaneExtractReceiptSchema,
    route: '/v1/invoicelane/receipt/extract',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.receipt.extract',
    estimatedCredits: 20,
  },
  {
    name: 'invoicelane_extract_invoice',
    description:
      'Extract an invoice as structured JSON (invoiceNumber, vendor, subtotal, tax, total, line items, missingFields, totalsConsistent). Schema requires invoiceNumber, total, currency, date. Provide raw invoice text. 30 credits.',
    inputSchema: invoicelaneExtractInvoiceSchema,
    route: '/v1/invoicelane/invoice/extract',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.invoice.extract',
    estimatedCredits: 30,
  },
  {
    name: 'invoicelane_validate',
    description:
      'Validate extracted fields against the InvoiceLane schema contract. Checks required fields, numeric totals, and totals consistency (subtotal + tax - discount ≈ total). Returns valid, missingFields, warnings, normalized. 10 credits.',
    inputSchema: invoicelaneValidateSchema,
    route: '/v1/invoicelane/validate',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.validate',
    estimatedCredits: 10,
  },
  {
    name: 'invoicelane_export_csv',
    description:
      'Export an array of extracted invoice/receipt row objects to CSV (escaped headers and values). 5 credits.',
    inputSchema: invoicelaneExportCsvSchema,
    route: '/v1/invoicelane/export/csv',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.export.csv',
    estimatedCredits: 5,
  },
  {
    name: 'geolane_health',
    description: 'Check GeoLane AI Visibility API health and endpoints. Free (no credits).',
    inputSchema: geolaneHealthSchema,
    route: '/v1/geolane/health',
    method: 'GET',
    product: 'geolane',
    action: 'geolane.health',
    estimatedCredits: null,
  },
  {
    name: 'geolane_pricing',
    description:
      'Get GeoLane credit pricing: audit 40, crawlers 15, llms_txt 20, citation_readiness 25, compare 50. Free.',
    inputSchema: geolanePricingSchema,
    route: '/v1/geolane/pricing',
    method: 'GET',
    product: 'geolane',
    action: 'geolane.pricing',
    estimatedCredits: null,
  },
  {
    name: 'geolane_capabilities',
    description:
      'List GeoLane capabilities: GEO score, AI crawler matrix, citation readiness, llms.txt draft, domain compare. Free.',
    inputSchema: geolaneCapabilitiesSchema,
    route: '/v1/geolane/capabilities',
    method: 'GET',
    product: 'geolane',
    action: 'geolane.capabilities',
    estimatedCredits: null,
  },
  {
    name: 'geolane_audit',
    description:
      'Full AI search visibility (GEO) audit for a URL: composite score/grade, AI crawler access, citation readiness, llms.txt, prioritized action plan. Pay-per-domain intelligence agents use before SEO/content work. 40 credits.',
    inputSchema: geolaneAuditSchema,
    route: '/v1/geolane/audit',
    method: 'POST',
    product: 'geolane',
    action: 'geolane.audit',
    estimatedCredits: 40,
  },
  {
    name: 'geolane_crawlers',
    description:
      'Check whether major AI crawlers (GPTBot, ClaudeBot, PerplexityBot, Google-Extended, etc.) are allowed in robots.txt. 15 credits.',
    inputSchema: geolaneCrawlersSchema,
    route: '/v1/geolane/crawlers',
    method: 'POST',
    product: 'geolane',
    action: 'geolane.crawlers',
    estimatedCredits: 15,
  },
  {
    name: 'geolane_llms_txt',
    description:
      'Detect /llms.txt, score quality, and generate a ready-to-publish llms.txt draft for AI agents. 20 credits.',
    inputSchema: geolaneLlmsTxtSchema,
    route: '/v1/geolane/llms-txt',
    method: 'POST',
    product: 'geolane',
    action: 'geolane.llms_txt',
    estimatedCredits: 20,
  },
  {
    name: 'geolane_citation_readiness',
    description:
      'Score a page for AI citation readiness: title, meta, H1, JSON-LD, author/date, FAQ, passage length (~134–167 words), headings. Returns gaps and recommendations. 25 credits.',
    inputSchema: geolaneCitationReadinessSchema,
    route: '/v1/geolane/citation-readiness',
    method: 'POST',
    product: 'geolane',
    action: 'geolane.citation_readiness',
    estimatedCredits: 25,
  },
  {
    name: 'geolane_compare',
    description:
      'Compare two domains/pages on GEO score, crawler access, citation readiness, and llms.txt. Provide urlA and urlB. 50 credits.',
    inputSchema: geolaneCompareSchema,
    route: '/v1/geolane/compare',
    method: 'POST',
    product: 'geolane',
    action: 'geolane.compare',
    estimatedCredits: 50,
  },
  {
    name: 'skills_generate_github_profile',
    description: 'Generate an installable AI skill from a public GitHub profile. Provide a GitHub username.',
    inputSchema: skillsGenerateProfileSchema,
    route: '/v1/skills/generate/github-profile',
    method: 'POST',
    product: 'skills',
    action: 'generate.github_profile',
    estimatedCredits: 80,
  },
  {
    name: 'skills_generate_github_repo',
    description: 'Generate an installable AI skill from a public GitHub repository. Provide the full repo URL.',
    inputSchema: skillsGenerateRepoSchema,
    route: '/v1/skills/generate/github-repo',
    method: 'POST',
    product: 'skills',
    action: 'generate.github_repo',
    estimatedCredits: 100,
  },
  {
    name: 'skills_generate_docs',
    description: 'Generate an installable AI skill from a documentation URL. Provide the full docs URL.',
    inputSchema: skillsGenerateDocsSchema,
    route: '/v1/skills/generate/docs',
    method: 'POST',
    product: 'skills',
    action: 'generate.docs',
    estimatedCredits: 100,
  },
  {
    name: 'skills_generate_text',
    description: 'Generate an installable AI skill from raw text content. Provide a name and the text content.',
    inputSchema: skillsGenerateTextSchema,
    route: '/v1/skills/generate/text',
    method: 'POST',
    product: 'skills',
    action: 'generate.text',
    estimatedCredits: 40,
  },
  {
    name: 'skills_export_cursor',
    description: 'Export a generated skill as Cursor-compatible files (SKILL.md, .cursorrules). Provide the skill object with name and skillMd.',
    inputSchema: skillsExportCursorSchema,
    route: '/v1/skills/export/cursor',
    method: 'POST',
    product: 'skills',
    action: 'export.cursor',
    estimatedCredits: 10,
  },
  {
    name: 'skills_export_claude',
    description: 'Export a generated skill as Claude Code-compatible files (SKILL.md, CLAUDE.md). Provide the skill object with name and skillMd.',
    inputSchema: skillsExportClaudeSchema,
    route: '/v1/skills/export/claude',
    method: 'POST',
    product: 'skills',
    action: 'export.claude',
    estimatedCredits: 10,
  },
  {
    name: 'ugclane_strategy_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate a content strategy based on goals, niche, and platform.',
    inputSchema: ugclaneStrategyGenerateSchema,
    route: '/v1/ugclane/strategy/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.strategy.generate',
    estimatedCredits: 30,
  },
  {
    name: 'ugclane_competitor_analyze',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Analyze competitor content strategies and patterns.',
    inputSchema: ugclaneCompetitorAnalyzeSchema,
    route: '/v1/ugclane/competitor/analyze',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.competitor.analyze',
    estimatedCredits: 40,
  },
  {
    name: 'ugclane_hooks_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate attention-grabbing hooks for content.',
    inputSchema: ugclaneHooksGenerateSchema,
    route: '/v1/ugclane/hooks/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.hooks.generate',
    estimatedCredits: 20,
  },
  {
    name: 'ugclane_scripts_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate video or post scripts for content.',
    inputSchema: ugclaneScriptsGenerateSchema,
    route: '/v1/ugclane/scripts/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.scripts.generate',
    estimatedCredits: 40,
  },
  {
    name: 'ugclane_accounts_plan',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Plan account growth strategy for a social platform.',
    inputSchema: ugclaneAccountsPlanSchema,
    route: '/v1/ugclane/accounts/plan',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.accounts.plan',
    estimatedCredits: 30,
  },
  {
    name: 'ugclane_calendar_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate a content calendar for a month.',
    inputSchema: ugclaneCalendarGenerateSchema,
    route: '/v1/ugclane/calendar/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.calendar.generate',
    estimatedCredits: 60,
  },
  {
    name: 'ugclane_experiments_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Design content experiments to optimize performance.',
    inputSchema: ugclaneExperimentsGenerateSchema,
    route: '/v1/ugclane/experiments/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.experiments.generate',
    estimatedCredits: 30,
  },
  {
    name: 'ugclane_report_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate a performance report for content.',
    inputSchema: ugclaneReportGenerateSchema,
    route: '/v1/ugclane/report/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.report.generate',
    estimatedCredits: 40,
  },
  {
    name: 'ugclane_export_markdown',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Export UGCLane output as markdown.',
    inputSchema: ugclaneExportMarkdownSchema,
    route: '/v1/ugclane/export/markdown',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.export.markdown',
    estimatedCredits: 5,
  },
  {
    name: 'ugclane_export_json',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Export UGCLane output as JSON.',
    inputSchema: ugclaneExportJsonSchema,
    route: '/v1/ugclane/export/json',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.export.json',
    estimatedCredits: 5,
  },
  {
    name: 'signallane_x_analyze',
    description: 'Analyze X (Twitter) account metrics for growth signals',
    inputSchema: signallaneXAnalyzeSchema,
    route: '/v1/signallane/x/analyze',
    method: 'POST',
    product: 'signallane',
    action: 'x.analyze',
    estimatedCredits: 30,
  },
  {
    name: 'signallane_x_content_plan',
    description: 'Generate a weekly content strategy for X',
    inputSchema: signallaneXContentPlanSchema,
    route: '/v1/signallane/x/content-plan',
    method: 'POST',
    product: 'signallane',
    action: 'x.content_plan',
    estimatedCredits: 40,
  },
  {
    name: 'signallane_x_post_drafts',
    description: 'Generate post drafts for X',
    inputSchema: signallaneXPostDraftsSchema,
    route: '/v1/signallane/x/post-drafts',
    method: 'POST',
    product: 'signallane',
    action: 'x.post_drafts',
    estimatedCredits: 40,
  },
  {
    name: 'signallane_x_experiments',
    description: 'Design content experiments for X',
    inputSchema: signallaneXExperimentsSchema,
    route: '/v1/signallane/x/experiments',
    method: 'POST',
    product: 'signallane',
    action: 'x.experiments',
    estimatedCredits: 30,
  },
  {
    name: 'webdatalane_fetch',
    description: 'Fetch a webpage by URL and return its HTML and text content.',
    inputSchema: webdatalaneFetchSchema,
    route: '/v1/webdatalane/fetch',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.fetch',
    estimatedCredits: 5,
  },
  {
    name: 'webdatalane_extract',
    description: 'Extract all content from a webpage: markdown, metadata, links, headings, images, JSON-LD, and tables.',
    inputSchema: webdatalaneExtractSchema,
    route: '/v1/webdatalane/extract',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.extract',
    estimatedCredits: 10,
  },
  {
    name: 'webdatalane_markdown',
    description: 'Convert a webpage or HTML to clean markdown. Optionally strip navigation elements.',
    inputSchema: webdatalaneMarkdownSchema,
    route: '/v1/webdatalane/markdown',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.markdown',
    estimatedCredits: 10,
  },
  {
    name: 'webdatalane_metadata',
    description: 'Extract metadata from a webpage: title, description, canonical, OpenGraph, Twitter card, and JSON-LD count.',
    inputSchema: webdatalaneMetadataSchema,
    route: '/v1/webdatalane/metadata',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.metadata',
    estimatedCredits: 5,
  },
  {
    name: 'webdatalane_links',
    description: 'Extract all links from a webpage, classified as internal or external.',
    inputSchema: webdatalaneLinksSchema,
    route: '/v1/webdatalane/links',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.links',
    estimatedCredits: 5,
  },
  {
    name: 'webdatalane_structured',
    description: 'Extract structured data fields from a webpage using a schema and hints.',
    inputSchema: webdatalaneStructuredSchema,
    route: '/v1/webdatalane/structured',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.structured',
    estimatedCredits: 20,
  },
  {
    name: 'webdatalane_crawl_plan',
    description: 'Generate a crawl plan from a seed URL, discovering internal and external links for multi-page extraction.',
    inputSchema: webdatalaneCrawlPlanSchema,
    route: '/v1/webdatalane/crawl/plan',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.crawl.plan',
    estimatedCredits: 15,
  },
  {
    name: 'webdatalane_screenshot',
    description: 'Capture a screenshot of a webpage. Note: not available in v0.1, returns BROWSER_RENDERING_NOT_AVAILABLE.',
    inputSchema: webdatalaneScreenshotSchema,
    route: '/v1/webdatalane/screenshot',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.screenshot',
    estimatedCredits: 50,
  },
  {
    name: 'signallane_x_report',
    description: 'Generate a full X growth intelligence report',
    inputSchema: signallaneXReportSchema,
    route: '/v1/signallane/x/report',
    method: 'POST',
    product: 'signallane',
    action: 'x.report',
    estimatedCredits: 60,
  },
  {
    name: 'crawlerlane_logs_ingest',
    description: 'Ingest access logs from a website you own. Logs may contain sensitive data — redact IPs before sending. Bot classification is heuristic.',
    inputSchema: crawlerlaneLogsIngestSchema,
    route: '/v1/crawlerlane/logs/ingest',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.logs.ingest',
    estimatedCredits: 5,
  },
  {
    name: 'crawlerlane_bots_classify',
    description: 'Classify a user-agent as bot or human. Heuristic only — not guaranteed identity.',
    inputSchema: crawlerlaneBotsClassifySchema,
    route: '/v1/crawlerlane/bots/classify',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.bots.classify',
    estimatedCredits: 2,
  },
  {
    name: 'crawlerlane_pages_analyze',
    description: 'Analyze crawl coverage and bot traffic by page for a domain you own.',
    inputSchema: crawlerlanePagesAnalyzeSchema,
    route: '/v1/crawlerlane/pages/analyze',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.pages.analyze',
    estimatedCredits: 20,
  },
  {
    name: 'crawlerlane_404_analyze',
    description: 'Find missing pages requested by bots and crawlers on a domain you own.',
    inputSchema: crawlerlane404AnalyzeSchema,
    route: '/v1/crawlerlane/404/analyze',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.404.analyze',
    estimatedCredits: 20,
  },
  {
    name: 'crawlerlane_ai_visibility_score',
    description: 'Score AI visibility for a domain you own based on bot crawl signals.',
    inputSchema: crawlerlaneAiVisibilityScoreSchema,
    route: '/v1/crawlerlane/ai-visibility/score',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.ai_visibility.score',
    estimatedCredits: 30,
  },
  {
    name: 'crawlerlane_report_generate',
    description: 'Generate a weekly crawler intelligence report for a domain you own.',
    inputSchema: crawlerlaneReportGenerateSchema,
    route: '/v1/crawlerlane/report/generate',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.report.generate',
    estimatedCredits: 40,
  },
  {
    name: 'crawlerlane_sitemap_suggest',
    description: 'Suggest sitemap entries and redirects based on crawl and 404 signals.',
    inputSchema: crawlerlaneSitemapSuggestSchema,
    route: '/v1/crawlerlane/sitemap/suggest',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.sitemap.suggest',
    estimatedCredits: 20,
  },
  {
    name: 'crawlerlane_robots_audit',
    description: 'Audit robots.txt for AI crawler and search engine visibility.',
    inputSchema: crawlerlaneRobotsAuditSchema,
    route: '/v1/crawlerlane/robots/audit',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.robots.audit',
    estimatedCredits: 15,
  },
  {
    name: 'crawlerlane_export_markdown',
    description: 'Export a CrawlerLane report as markdown.',
    inputSchema: crawlerlaneExportMarkdownSchema,
    route: '/v1/crawlerlane/export/markdown',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.export.markdown',
    estimatedCredits: 5,
  },
  {
    name: 'crawlerlane_export_json',
    description: 'Export a CrawlerLane report as JSON.',
    inputSchema: crawlerlaneExportJsonSchema,
    route: '/v1/crawlerlane/export/json',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.export.json',
    estimatedCredits: 5,
  },
  {
    name: 'opensourcelane_repo_analyze',
    description: 'Analyze an open-source repo for adoption fit. Risk scores are heuristic — not security audits.',
    inputSchema: opensourcelaneRepoAnalyzeSchema,
    route: '/v1/opensourcelane/repo/analyze',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.repo.analyze',
    estimatedCredits: 25,
  },
  {
    name: 'opensourcelane_alternatives_find',
    description: 'Find open-source alternatives to expensive SaaS tools.',
    inputSchema: opensourcelaneAlternativesFindSchema,
    route: '/v1/opensourcelane/alternatives/find',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.alternatives.find',
    estimatedCredits: 30,
  },
  {
    name: 'opensourcelane_migration_plan',
    description: 'Generate a migration plan from SaaS to open-source. Not legal or financial advice.',
    inputSchema: opensourcelaneMigrationPlanSchema,
    route: '/v1/opensourcelane/migration/plan',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.migration.plan',
    estimatedCredits: 50,
  },
  {
    name: 'opensourcelane_cost_estimate',
    description: 'Estimate cost savings from switching to open-source. Estimates only — not financial advice.',
    inputSchema: opensourcelaneCostEstimateSchema,
    route: '/v1/opensourcelane/cost/estimate',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.cost.estimate',
    estimatedCredits: 20,
  },
  {
    name: 'opensourcelane_risk_score',
    description: 'Score adoption risk heuristically. Not a security audit.',
    inputSchema: opensourcelaneRiskScoreSchema,
    route: '/v1/opensourcelane/risk/score',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.risk.score',
    estimatedCredits: 30,
  },
  {
    name: 'opensourcelane_brief_generate',
    description: 'Generate an adoption brief for an open-source tool.',
    inputSchema: opensourcelaneBriefGenerateSchema,
    route: '/v1/opensourcelane/brief/generate',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.brief.generate',
    estimatedCredits: 40,
  },
  {
    name: 'opensourcelane_tools_compare',
    description: 'Compare multiple open-source tools side by side.',
    inputSchema: opensourcelaneToolsCompareSchema,
    route: '/v1/opensourcelane/tools/compare',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.tools.compare',
    estimatedCredits: 35,
  },
  {
    name: 'opensourcelane_deployment_plan',
    description: 'Generate a self-hosting deployment plan.',
    inputSchema: opensourcelaneDeploymentPlanSchema,
    route: '/v1/opensourcelane/deployment/plan',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.deployment.plan',
    estimatedCredits: 35,
  },
  {
    name: 'opensourcelane_license_audit',
    description: 'Audit license obligations. Not legal advice.',
    inputSchema: opensourcelaneLicenseAuditSchema,
    route: '/v1/opensourcelane/license/audit',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.license.audit',
    estimatedCredits: 20,
  },
  {
    name: 'opensourcelane_export_markdown',
    description: 'Export OpenSourceLane analysis as markdown.',
    inputSchema: opensourcelaneExportMarkdownSchema,
    route: '/v1/opensourcelane/export/markdown',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.export.markdown',
    estimatedCredits: 5,
  },
  {
    name: 'opensourcelane_export_json',
    description: 'Export OpenSourceLane analysis as JSON.',
    inputSchema: opensourcelaneExportJsonSchema,
    route: '/v1/opensourcelane/export/json',
    method: 'POST',
    product: 'opensourcelane',
    action: 'opensourcelane.export.json',
    estimatedCredits: 5,
  },
  {
    name: 'forgecad_design_generate',
    description: 'Generate parametric CAD design with OpenSCAD, BOM, and manufacturing notes. Human engineering review required. Not certified engineering software.',
    inputSchema: forgecadDesignGenerateSchema,
    route: '/v1/forgecad/design/generate',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.design.generate',
    estimatedCredits: 60,
  },
  {
    name: 'forgecad_openscad_generate',
    description: 'Generate parametric OpenSCAD script. Draft only — human review required.',
    inputSchema: forgecadOpenScadGenerateSchema,
    route: '/v1/forgecad/openscad/generate',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.openscad.generate',
    estimatedCredits: 40,
  },
  {
    name: 'forgecad_bom_generate',
    description: 'Generate bill of materials for a CAD project.',
    inputSchema: forgecadBomGenerateSchema,
    route: '/v1/forgecad/bom/generate',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.bom.generate',
    estimatedCredits: 20,
  },
  {
    name: 'forgecad_cutlist_generate',
    description: 'Generate cut list for frames and panels.',
    inputSchema: forgecadCutlistGenerateSchema,
    route: '/v1/forgecad/cutlist/generate',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.cutlist.generate',
    estimatedCredits: 20,
  },
  {
    name: 'forgecad_assembly_plan',
    description: 'Generate assembly plan steps. Human review required.',
    inputSchema: forgecadAssemblyPlanSchema,
    route: '/v1/forgecad/assembly/plan',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.assembly.plan',
    estimatedCredits: 25,
  },
  {
    name: 'forgecad_printability_check',
    description: 'Check FDM 3D printability heuristically. Not a certified DFM analysis.',
    inputSchema: forgecadPrintabilityCheckSchema,
    route: '/v1/forgecad/printability/check',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.printability.check',
    estimatedCredits: 25,
  },
  {
    name: 'forgecad_manufacturability_check',
    description: 'Check manufacturability for laser cutting, sheet metal, etc. Informational only.',
    inputSchema: forgecadManufacturabilityCheckSchema,
    route: '/v1/forgecad/manufacturability/check',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.manufacturability.check',
    estimatedCredits: 30,
  },
  {
    name: 'forgecad_design_review',
    description: 'Generate design review report. Not a certified engineering review.',
    inputSchema: forgecadDesignReviewSchema,
    route: '/v1/forgecad/design/review',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.design.review',
    estimatedCredits: 40,
  },
  {
    name: 'forgecad_material_estimate',
    description: 'Estimate material usage for a design.',
    inputSchema: forgecadMaterialEstimateSchema,
    route: '/v1/forgecad/material/estimate',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.material.estimate',
    estimatedCredits: 20,
  },
  {
    name: 'forgecad_tools_detect',
    description: 'Detect OpenSCAD and FreeCAD installation.',
    inputSchema: forgecadToolsDetectSchema,
    route: '/v1/forgecad/tools/detect',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.tools.detect',
    estimatedCredits: 5,
  },
  {
    name: 'forgecad_render_openscad',
    description: 'Render OpenSCAD to STL/PNG if OpenSCAD is installed. Returns TOOL_NOT_AVAILABLE otherwise.',
    inputSchema: forgecadRenderOpenScadSchema,
    route: '/v1/forgecad/render/openscad',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.render.openscad',
    estimatedCredits: 80,
  },
  {
    name: 'forgecad_export_markdown',
    description: 'Export ForgeCAD design report as markdown.',
    inputSchema: forgecadExportMarkdownSchema,
    route: '/v1/forgecad/export/markdown',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.export.markdown',
    estimatedCredits: 5,
  },
  {
    name: 'forgecad_export_json',
    description: 'Export ForgeCAD design as JSON.',
    inputSchema: forgecadExportJsonSchema,
    route: '/v1/forgecad/export/json',
    method: 'POST',
    product: 'forgecad',
    action: 'forgecad.export.json',
    estimatedCredits: 5,
  },
  {
    name: 'replylane_opportunity_score',
    description: 'Score an X tweet for strategic reply opportunity (timing, author size, competition).',
    inputSchema: replylaneOpportunityScoreSchema,
    route: '/v1/replylane/opportunity/score',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.opportunity.score',
    estimatedCredits: 15,
  },
  {
    name: 'replylane_targets_rank',
    description: 'Rank X accounts for reply targeting in the 5-20x follower sweet spot.',
    inputSchema: replylaneTargetsRankSchema,
    route: '/v1/replylane/targets/rank',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.targets.rank',
    estimatedCredits: 25,
  },
  {
    name: 'replylane_replies_draft',
    description: 'Draft strategic X replies (data, experience, insight, question, etc.). Human review required.',
    inputSchema: replylaneRepliesDraftSchema,
    route: '/v1/replylane/replies/draft',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.replies.draft',
    estimatedCredits: 30,
  },
  {
    name: 'replylane_replies_risk',
    description: 'Score X reply deboost/spam risk before posting.',
    inputSchema: replylaneRepliesRiskSchema,
    route: '/v1/replylane/replies/risk',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.replies.risk',
    estimatedCredits: 20,
  },
  {
    name: 'replylane_posts_grok_check',
    description: 'Check Grok/constructive tone compatibility for an X post or reply draft.',
    inputSchema: replylanePostsGrokCheckSchema,
    route: '/v1/replylane/posts/grok-check',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.posts.grok_check',
    estimatedCredits: 20,
  },
  {
    name: 'replylane_activity_audit',
    description: 'Audit 70/30 reply vs post activity balance.',
    inputSchema: replylaneActivityAuditSchema,
    route: '/v1/replylane/activity/audit',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.activity.audit',
    estimatedCredits: 35,
  },
  {
    name: 'replylane_feeds_migrate',
    description: 'Plan migration from X Communities to XChat groups and Custom Timelines.',
    inputSchema: replylaneFeedsMigrateSchema,
    route: '/v1/replylane/feeds/migrate',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.feeds.migrate',
    estimatedCredits: 40,
  },
  {
    name: 'replylane_export_markdown',
    description: 'Export ReplyLane report as markdown.',
    inputSchema: replylaneExportMarkdownSchema,
    route: '/v1/replylane/export/markdown',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.export.markdown',
    estimatedCredits: 5,
  },
  {
    name: 'replylane_export_json',
    description: 'Export ReplyLane report as JSON.',
    inputSchema: replylaneExportJsonSchema,
    route: '/v1/replylane/export/json',
    method: 'POST',
    product: 'replylane',
    action: 'replylane.export.json',
    estimatedCredits: 5,
  },
  {
    name: 'tradia_health',
    description: 'Check Tradia API health and available endpoints.',
    inputSchema: tradiaHealthSchema,
    route: '/v1/tradia/health',
    method: 'GET',
    product: 'tradia',
    action: 'tradia.health',
    estimatedCredits: null,
  },
  {
    name: 'tradia_agent_plan',
    description: 'Generate a personalized trading plan based on goals, risk tolerance, and market preferences. Not financial advice.',
    inputSchema: tradiaAgentPlanSchema,
    route: '/v1/tradia/agent/plan',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.agent.plan',
    estimatedCredits: 40,
  },
  {
    name: 'tradia_market_analyze',
    description: 'Analyze a market or asset for trading opportunities using technical indicators. Not financial advice.',
    inputSchema: tradiaMarketAnalyzeSchema,
    route: '/v1/tradia/market/analyze',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.market.analyze',
    estimatedCredits: 30,
  },
  {
    name: 'tradia_signal_evaluate',
    description: 'Evaluate a trading signal or setup for quality and risk. Not financial advice.',
    inputSchema: tradiaSignalEvaluateSchema,
    route: '/v1/tradia/signal/evaluate',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.signal.evaluate',
    estimatedCredits: 30,
  },
  {
    name: 'tradia_risk_check',
    description: 'Check trade risk parameters including R-multiple, risk percentage, and position sizing. Not financial advice.',
    inputSchema: tradiaRiskCheckSchema,
    route: '/v1/tradia/risk/check',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.risk.check',
    estimatedCredits: 20,
  },
  {
    name: 'tradia_trade_propose',
    description: 'Propose a trade setup with entry, stop loss, take profit, and rationale. Not financial advice.',
    inputSchema: tradiaTradeProposeSchema,
    route: '/v1/tradia/trade/propose',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.trade.propose',
    estimatedCredits: 40,
  },
  {
    name: 'tradia_trade_journal',
    description: 'Journal a trade with entry/exit details, P&L, and reflections. Not financial advice.',
    inputSchema: tradiaTradeJournalSchema,
    route: '/v1/tradia/trade/journal',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.trade.journal',
    estimatedCredits: 25,
  },
  {
    name: 'tradia_portfolio_report',
    description: 'Generate a portfolio health report with allocation analysis and diversification scoring. Not financial advice.',
    inputSchema: tradiaPortfolioReportSchema,
    route: '/v1/tradia/portfolio/report',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.portfolio.report',
    estimatedCredits: 50,
  },
  {
    name: 'tradia_performance_analyze',
    description: 'Analyze trading performance including win rate, profit factor, drawdown, and Sharpe-like scoring. Not financial advice.',
    inputSchema: tradiaPerformanceAnalyzeSchema,
    route: '/v1/tradia/performance/analyze',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.performance.analyze',
    estimatedCredits: 35,
  },
  {
    name: 'tradia_public_update_generate',
    description: 'Generate a public trading update/loss-porn post for social platforms based on recent trades. Not financial advice.',
    inputSchema: tradiaPublicUpdateGenerateSchema,
    route: '/v1/tradia/public-update/generate',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.public_update.generate',
    estimatedCredits: 30,
  },
  {
    name: 'tradia_backtest_simulate',
    description: 'Simulate a trading strategy backtest over historical data. Not financial advice.',
    inputSchema: tradiaBacktestSimulateSchema,
    route: '/v1/tradia/backtest/simulate',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.backtest.simulate',
    estimatedCredits: 60,
  },
  {
    name: 'tradia_accountability_card',
    description: 'Generate an accountability card reviewing trade discipline, mistakes, and lessons. Not financial advice.',
    inputSchema: tradiaAccountabilityCardSchema,
    route: '/v1/tradia/accountability/card',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.accountability.card',
    estimatedCredits: 25,
  },
  {
    name: 'tradia_export_markdown',
    description: 'Export Tradia trade data as a formatted markdown report.',
    inputSchema: tradiaExportMarkdownSchema,
    route: '/v1/tradia/export/markdown',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.export.markdown',
    estimatedCredits: 5,
  },
  {
    name: 'tradia_export_json',
    description: 'Export Tradia trade data as JSON.',
    inputSchema: tradiaExportJsonSchema,
    route: '/v1/tradia/export/json',
    method: 'POST',
    product: 'tradia',
    action: 'tradia.export.json',
    estimatedCredits: 5,
  },
]

export const TOOL_MAP = new Map(ALL_TOOLS.map((t) => [t.name, t]))
export const TOOL_NAMES = ALL_TOOLS.map((t) => t.name)
