import { createProductClient } from './product-client'
import { mapHttpStatusToMcpError, MCP_ERROR_CODES } from './errors'
import {
  teraWritingRewriteSchema,
  teraWritingDraftSchema,
  teraCodingExplainSchema,
  teraCodingReviewSchema,
  routerChatSchema,
  agentBrowserCheckSchema,
  agentBrowserScreenshotSchema,
  agentBrowserTraceReportSchema,
  cliploopBriefGenerateSchema,
  cliploopScriptGenerateSchema,
  cliploopVideoRenderSchema,
  cliploopCampaignCreateSchema,
  cliploopCampaignPackageSchema,
  cloudPricingSchema,
  skillsGenerateProfileSchema,
  skillsGenerateRepoSchema,
  skillsGenerateDocsSchema,
  skillsGenerateTextSchema,
  skillsExportCursorSchema,
  skillsExportClaudeSchema,
  invoicelaneExtractSchema,
  invoicelaneExtractReceiptSchema,
  invoicelaneExtractInvoiceSchema,
  invoicelaneValidateSchema,
  invoicelaneExportCsvSchema,
  webdatalaneFetchSchema,
  webdatalaneExtractSchema,
  webdatalaneMarkdownSchema,
  webdatalaneMetadataSchema,
  webdatalaneLinksSchema,
  webdatalaneStructuredSchema,
  webdatalaneCrawlPlanSchema,
  webdatalaneScreenshotSchema,
  crawlerlaneLogsIngestSchema,
  crawlerlaneBotsClassifySchema,
  crawlerlanePagesAnalyzeSchema,
  crawlerlane404AnalyzeSchema,
  crawlerlaneAiVisibilityScoreSchema,
  crawlerlaneReportGenerateSchema,
  crawlerlaneSitemapSuggestSchema,
  crawlerlaneRobotsAuditSchema,
  crawlerlaneExportMarkdownSchema,
  crawlerlaneExportJsonSchema,
  signallaneXAnalyzeSchema,
  signallaneXContentPlanSchema,
  signallaneXPostDraftsSchema,
  signallaneXExperimentsSchema,
  signallaneXReportSchema,
  ugclaneStrategyGenerateSchema,
  ugclaneCompetitorAnalyzeSchema,
  ugclaneHooksGenerateSchema,
  ugclaneScriptsGenerateSchema,
  ugclaneAccountsPlanSchema,
  ugclaneCalendarGenerateSchema,
  ugclaneExperimentsGenerateSchema,
  ugclaneReportGenerateSchema,
  ugclaneExportMarkdownSchema,
  ugclaneExportJsonSchema,
} from './schemas'
import type { McpToolDefinition, McpToolResult } from './types'

export interface ToolContext {
  apiKey: string
}

export async function callTool(
  tool: McpToolDefinition,
  args: Record<string, unknown> | undefined,
  ctx: ToolContext,
): Promise<McpToolResult> {
  const client = createProductClient(ctx.apiKey)

  const body = tool.method === 'POST' ? args : undefined
  console.error('DEBUG: tool=%s method=%s body=%s', tool.name, tool.method, JSON.stringify(body))
  const result = await client.request(tool.method, tool.route, body)

  if (!result.ok) {
    const mcpError = mapHttpStatusToMcpError(result.status, result.body)
    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify({ ok: false, error: mcpError.message, code: mcpError.code, data: mcpError.data ?? null }),
        },
      ],
      isError: true,
    }
  }

  return {
    content: [
      {
        type: 'text',
        text: JSON.stringify({ ok: true, data: result.body }),
      },
    ],
  }
}

export const ALL_TOOLS: McpToolDefinition[] = [
  {
    name: 'tera_writing_rewrite',
    description: 'Rewrite text with a specific style and tone using Tera. Provide text to rewrite and optional style/tone/maxLength parameters.',
    inputSchema: teraWritingRewriteSchema,
    route: '/v1/tera/writing/rewrite',
    method: 'POST',
    product: 'tera',
    action: 'writing.rewrite',
    estimatedCredits: 5,
  },
  {
    name: 'tera_writing_draft',
    description: 'Draft content (email, social post, announcement, article, doc) using Tera. Provide type and brief describing what to write.',
    inputSchema: teraWritingDraftSchema,
    route: '/v1/tera/writing/draft',
    method: 'POST',
    product: 'tera',
    action: 'writing.draft',
    estimatedCredits: 10,
  },
  {
    name: 'tera_coding_explain',
    description: 'Explain code at beginner, intermediate, or advanced level using Tera. Provide language and code snippet.',
    inputSchema: teraCodingExplainSchema,
    route: '/v1/tera/coding/explain',
    method: 'POST',
    product: 'tera',
    action: 'coding.explain',
    estimatedCredits: 10,
  },
  {
    name: 'tera_coding_review',
    description: 'Review code for issues, bugs, security, and performance using Tera. Provide language and code to review.',
    inputSchema: teraCodingReviewSchema,
    route: '/v1/tera/coding/review',
    method: 'POST',
    product: 'tera',
    action: 'coding.review',
    estimatedCredits: 20,
  },
  {
    name: 'router_chat',
    description: 'Send a chat completion to the Talocode router. Supports talocode/auto, talocode/fast, talocode/coding and provider-specific models.',
    inputSchema: routerChatSchema,
    route: '/v1/router/chat/completions',
    method: 'POST',
    product: 'router',
    action: 'chat.completions',
    estimatedCredits: null,
  },
  {
    name: 'agent_browser_check',
    description: 'Check a website URL for status, content, and optionally capture a screenshot or run vision analysis. Provide URL to check.',
    inputSchema: agentBrowserCheckSchema,
    route: '/v1/agent-browser/check',
    method: 'POST',
    product: 'agent_browser',
    action: 'browser.check',
    estimatedCredits: 5,
  },
  {
    name: 'agent_browser_screenshot',
    description: 'Capture a screenshot of a website URL. Optionally set fullPage, viewport width/height. Provide URL to screenshot.',
    inputSchema: agentBrowserScreenshotSchema,
    route: '/v1/agent-browser/screenshot',
    method: 'POST',
    product: 'agent_browser',
    action: 'browser.screenshot',
    estimatedCredits: 8,
  },
  {
    name: 'agent_browser_trace_report',
    description: 'Execute browser trace steps on a URL and report results. Provide URL and array of steps (click, type, navigate).',
    inputSchema: agentBrowserTraceReportSchema,
    route: '/v1/agent-browser/trace-report',
    method: 'POST',
    product: 'agent_browser',
    action: 'browser.trace_report',
    estimatedCredits: 15,
  },
  {
    name: 'cliploop_brief_generate',
    description: 'Generate a video brief for short-form content. Provide a prompt describing the video concept and optional channel/tone/duration.',
    inputSchema: cliploopBriefGenerateSchema,
    route: '/v1/cliploop/brief/generate',
    method: 'POST',
    product: 'cliploop',
    action: 'brief.generate',
    estimatedCredits: 15,
  },
  {
    name: 'cliploop_script_generate',
    description: 'Generate a video script from a brief. Provide the briefId from brief generation.',
    inputSchema: cliploopScriptGenerateSchema,
    route: '/v1/cliploop/script/generate',
    method: 'POST',
    product: 'cliploop',
    action: 'script.generate',
    estimatedCredits: 15,
  },
  {
    name: 'cliploop_video_render',
    description: 'Render a video from a script. Provide the scriptId from script generation and optional format/quality.',
    inputSchema: cliploopVideoRenderSchema,
    route: '/v1/cliploop/video/render',
    method: 'POST',
    product: 'cliploop',
    action: 'video.render',
    estimatedCredits: 200,
  },
  {
    name: 'cliploop_campaign_create',
    description: 'Create a ClipLoop campaign. Provide name and platform.',
    inputSchema: cliploopCampaignCreateSchema,
    route: '/v1/cliploop/campaign/create',
    method: 'POST',
    product: 'cliploop',
    action: 'campaign.create',
    estimatedCredits: 50,
  },
  {
    name: 'cliploop_campaign_package',
    description: 'Package a ClipLoop campaign for delivery. Provide campaignId.',
    inputSchema: cliploopCampaignPackageSchema,
    route: '/v1/cliploop/campaign/package',
    method: 'POST',
    product: 'cliploop',
    action: 'campaign.package',
    estimatedCredits: 400,
  },
  {
    name: 'cloud_pricing',
    description: 'Get the full Talocode Cloud pricing catalog with all products, actions, and credit costs.',
    inputSchema: cloudPricingSchema,
    route: '/api/v1/cloud/pricing',
    method: 'GET',
    product: 'cloud',
    action: 'pricing.list',
    estimatedCredits: null,
  },
  {
    name: 'invoicelane_extract',
    description: 'Extract structured data from invoice or receipt text. Provide raw text from an invoice or receipt document.',
    inputSchema: invoicelaneExtractSchema,
    route: '/v1/invoicelane/extract',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.extract',
    estimatedCredits: 20,
  },
  {
    name: 'invoicelane_extract_receipt',
    description: 'Extract structured data from receipt text specifically.',
    inputSchema: invoicelaneExtractReceiptSchema,
    route: '/v1/invoicelane/receipt/extract',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.receipt.extract',
    estimatedCredits: 20,
  },
  {
    name: 'invoicelane_extract_invoice',
    description: 'Extract structured data from invoice text specifically.',
    inputSchema: invoicelaneExtractInvoiceSchema,
    route: '/v1/invoicelane/invoice/extract',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.invoice.extract',
    estimatedCredits: 30,
  },
  {
    name: 'invoicelane_validate',
    description: 'Validate extracted invoice/receipt fields for completeness and correctness.',
    inputSchema: invoicelaneValidateSchema,
    route: '/v1/invoicelane/validate',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.validate',
    estimatedCredits: 10,
  },
  {
    name: 'invoicelane_export_csv',
    description: 'Export extracted invoice/receipt data as CSV.',
    inputSchema: invoicelaneExportCsvSchema,
    route: '/v1/invoicelane/export/csv',
    method: 'POST',
    product: 'invoicelane',
    action: 'invoicelane.export.csv',
    estimatedCredits: 5,
  },
  {
    name: 'skills_generate_github_profile',
    description: 'Generate an installable AI skill from a public GitHub profile. Provide a GitHub username.',
    inputSchema: skillsGenerateProfileSchema,
    route: '/v1/skills/generate/github-profile',
    method: 'POST',
    product: 'skills',
    action: 'generate.github_profile',
    estimatedCredits: 80,
  },
  {
    name: 'skills_generate_github_repo',
    description: 'Generate an installable AI skill from a public GitHub repository. Provide the full repo URL.',
    inputSchema: skillsGenerateRepoSchema,
    route: '/v1/skills/generate/github-repo',
    method: 'POST',
    product: 'skills',
    action: 'generate.github_repo',
    estimatedCredits: 100,
  },
  {
    name: 'skills_generate_docs',
    description: 'Generate an installable AI skill from a documentation URL. Provide the full docs URL.',
    inputSchema: skillsGenerateDocsSchema,
    route: '/v1/skills/generate/docs',
    method: 'POST',
    product: 'skills',
    action: 'generate.docs',
    estimatedCredits: 100,
  },
  {
    name: 'skills_generate_text',
    description: 'Generate an installable AI skill from raw text content. Provide a name and the text content.',
    inputSchema: skillsGenerateTextSchema,
    route: '/v1/skills/generate/text',
    method: 'POST',
    product: 'skills',
    action: 'generate.text',
    estimatedCredits: 40,
  },
  {
    name: 'skills_export_cursor',
    description: 'Export a generated skill as Cursor-compatible files (SKILL.md, .cursorrules). Provide the skill object with name and skillMd.',
    inputSchema: skillsExportCursorSchema,
    route: '/v1/skills/export/cursor',
    method: 'POST',
    product: 'skills',
    action: 'export.cursor',
    estimatedCredits: 10,
  },
  {
    name: 'skills_export_claude',
    description: 'Export a generated skill as Claude Code-compatible files (SKILL.md, CLAUDE.md). Provide the skill object with name and skillMd.',
    inputSchema: skillsExportClaudeSchema,
    route: '/v1/skills/export/claude',
    method: 'POST',
    product: 'skills',
    action: 'export.claude',
    estimatedCredits: 10,
  },
  {
    name: 'ugclane_strategy_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate a content strategy based on goals, niche, and platform.',
    inputSchema: ugclaneStrategyGenerateSchema,
    route: '/v1/ugclane/strategy/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.strategy.generate',
    estimatedCredits: 30,
  },
  {
    name: 'ugclane_competitor_analyze',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Analyze competitor content strategies and patterns.',
    inputSchema: ugclaneCompetitorAnalyzeSchema,
    route: '/v1/ugclane/competitor/analyze',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.competitor.analyze',
    estimatedCredits: 40,
  },
  {
    name: 'ugclane_hooks_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate attention-grabbing hooks for content.',
    inputSchema: ugclaneHooksGenerateSchema,
    route: '/v1/ugclane/hooks/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.hooks.generate',
    estimatedCredits: 20,
  },
  {
    name: 'ugclane_scripts_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate video or post scripts for content.',
    inputSchema: ugclaneScriptsGenerateSchema,
    route: '/v1/ugclane/scripts/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.scripts.generate',
    estimatedCredits: 40,
  },
  {
    name: 'ugclane_accounts_plan',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Plan account growth strategy for a social platform.',
    inputSchema: ugclaneAccountsPlanSchema,
    route: '/v1/ugclane/accounts/plan',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.accounts.plan',
    estimatedCredits: 30,
  },
  {
    name: 'ugclane_calendar_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate a content calendar for a month.',
    inputSchema: ugclaneCalendarGenerateSchema,
    route: '/v1/ugclane/calendar/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.calendar.generate',
    estimatedCredits: 60,
  },
  {
    name: 'ugclane_experiments_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Design content experiments to optimize performance.',
    inputSchema: ugclaneExperimentsGenerateSchema,
    route: '/v1/ugclane/experiments/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.experiments.generate',
    estimatedCredits: 30,
  },
  {
    name: 'ugclane_report_generate',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Generate a performance report for content.',
    inputSchema: ugclaneReportGenerateSchema,
    route: '/v1/ugclane/report/generate',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.report.generate',
    estimatedCredits: 40,
  },
  {
    name: 'ugclane_export_markdown',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Export UGCLane output as markdown.',
    inputSchema: ugclaneExportMarkdownSchema,
    route: '/v1/ugclane/export/markdown',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.export.markdown',
    estimatedCredits: 5,
  },
  {
    name: 'ugclane_export_json',
    description: 'UGCLane is a programmable UGC workflow engine for original content strategy, hooks, scripts, calendars, experiments and reporting. It performs ethical pattern analysis — not copying. Export UGCLane output as JSON.',
    inputSchema: ugclaneExportJsonSchema,
    route: '/v1/ugclane/export/json',
    method: 'POST',
    product: 'ugclane',
    action: 'ugclane.export.json',
    estimatedCredits: 5,
  },
  {
    name: 'signallane_x_analyze',
    description: 'Analyze X (Twitter) account metrics for growth signals',
    inputSchema: signallaneXAnalyzeSchema,
    route: '/v1/signallane/x/analyze',
    method: 'POST',
    product: 'signallane',
    action: 'x.analyze',
    estimatedCredits: 30,
  },
  {
    name: 'signallane_x_content_plan',
    description: 'Generate a weekly content strategy for X',
    inputSchema: signallaneXContentPlanSchema,
    route: '/v1/signallane/x/content-plan',
    method: 'POST',
    product: 'signallane',
    action: 'x.content_plan',
    estimatedCredits: 40,
  },
  {
    name: 'signallane_x_post_drafts',
    description: 'Generate post drafts for X',
    inputSchema: signallaneXPostDraftsSchema,
    route: '/v1/signallane/x/post-drafts',
    method: 'POST',
    product: 'signallane',
    action: 'x.post_drafts',
    estimatedCredits: 40,
  },
  {
    name: 'signallane_x_experiments',
    description: 'Design content experiments for X',
    inputSchema: signallaneXExperimentsSchema,
    route: '/v1/signallane/x/experiments',
    method: 'POST',
    product: 'signallane',
    action: 'x.experiments',
    estimatedCredits: 30,
  },
  {
    name: 'webdatalane_fetch',
    description: 'Fetch a webpage by URL and return its HTML and text content.',
    inputSchema: webdatalaneFetchSchema,
    route: '/v1/webdatalane/fetch',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.fetch',
    estimatedCredits: 5,
  },
  {
    name: 'webdatalane_extract',
    description: 'Extract all content from a webpage: markdown, metadata, links, headings, images, JSON-LD, and tables.',
    inputSchema: webdatalaneExtractSchema,
    route: '/v1/webdatalane/extract',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.extract',
    estimatedCredits: 10,
  },
  {
    name: 'webdatalane_markdown',
    description: 'Convert a webpage or HTML to clean markdown. Optionally strip navigation elements.',
    inputSchema: webdatalaneMarkdownSchema,
    route: '/v1/webdatalane/markdown',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.markdown',
    estimatedCredits: 10,
  },
  {
    name: 'webdatalane_metadata',
    description: 'Extract metadata from a webpage: title, description, canonical, OpenGraph, Twitter card, and JSON-LD count.',
    inputSchema: webdatalaneMetadataSchema,
    route: '/v1/webdatalane/metadata',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.metadata',
    estimatedCredits: 5,
  },
  {
    name: 'webdatalane_links',
    description: 'Extract all links from a webpage, classified as internal or external.',
    inputSchema: webdatalaneLinksSchema,
    route: '/v1/webdatalane/links',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.links',
    estimatedCredits: 5,
  },
  {
    name: 'webdatalane_structured',
    description: 'Extract structured data fields from a webpage using a schema and hints.',
    inputSchema: webdatalaneStructuredSchema,
    route: '/v1/webdatalane/structured',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.structured',
    estimatedCredits: 20,
  },
  {
    name: 'webdatalane_crawl_plan',
    description: 'Generate a crawl plan from a seed URL, discovering internal and external links for multi-page extraction.',
    inputSchema: webdatalaneCrawlPlanSchema,
    route: '/v1/webdatalane/crawl/plan',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.crawl.plan',
    estimatedCredits: 15,
  },
  {
    name: 'webdatalane_screenshot',
    description: 'Capture a screenshot of a webpage. Note: not available in v0.1, returns BROWSER_RENDERING_NOT_AVAILABLE.',
    inputSchema: webdatalaneScreenshotSchema,
    route: '/v1/webdatalane/screenshot',
    method: 'POST',
    product: 'webdatalane',
    action: 'webdatalane.screenshot',
    estimatedCredits: 50,
  },
  {
    name: 'signallane_x_report',
    description: 'Generate a full X growth intelligence report',
    inputSchema: signallaneXReportSchema,
    route: '/v1/signallane/x/report',
    method: 'POST',
    product: 'signallane',
    action: 'x.report',
    estimatedCredits: 60,
  },
  {
    name: 'crawlerlane_logs_ingest',
    description: 'Ingest access logs from a website you own. Logs may contain sensitive data — redact IPs before sending. Bot classification is heuristic.',
    inputSchema: crawlerlaneLogsIngestSchema,
    route: '/v1/crawlerlane/logs/ingest',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.logs.ingest',
    estimatedCredits: 5,
  },
  {
    name: 'crawlerlane_bots_classify',
    description: 'Classify a user-agent as bot or human. Heuristic only — not guaranteed identity.',
    inputSchema: crawlerlaneBotsClassifySchema,
    route: '/v1/crawlerlane/bots/classify',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.bots.classify',
    estimatedCredits: 2,
  },
  {
    name: 'crawlerlane_pages_analyze',
    description: 'Analyze crawl coverage and bot traffic by page for a domain you own.',
    inputSchema: crawlerlanePagesAnalyzeSchema,
    route: '/v1/crawlerlane/pages/analyze',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.pages.analyze',
    estimatedCredits: 20,
  },
  {
    name: 'crawlerlane_404_analyze',
    description: 'Find missing pages requested by bots and crawlers on a domain you own.',
    inputSchema: crawlerlane404AnalyzeSchema,
    route: '/v1/crawlerlane/404/analyze',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.404.analyze',
    estimatedCredits: 20,
  },
  {
    name: 'crawlerlane_ai_visibility_score',
    description: 'Score AI visibility for a domain you own based on bot crawl signals.',
    inputSchema: crawlerlaneAiVisibilityScoreSchema,
    route: '/v1/crawlerlane/ai-visibility/score',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.ai_visibility.score',
    estimatedCredits: 30,
  },
  {
    name: 'crawlerlane_report_generate',
    description: 'Generate a weekly crawler intelligence report for a domain you own.',
    inputSchema: crawlerlaneReportGenerateSchema,
    route: '/v1/crawlerlane/report/generate',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.report.generate',
    estimatedCredits: 40,
  },
  {
    name: 'crawlerlane_sitemap_suggest',
    description: 'Suggest sitemap entries and redirects based on crawl and 404 signals.',
    inputSchema: crawlerlaneSitemapSuggestSchema,
    route: '/v1/crawlerlane/sitemap/suggest',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.sitemap.suggest',
    estimatedCredits: 20,
  },
  {
    name: 'crawlerlane_robots_audit',
    description: 'Audit robots.txt for AI crawler and search engine visibility.',
    inputSchema: crawlerlaneRobotsAuditSchema,
    route: '/v1/crawlerlane/robots/audit',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.robots.audit',
    estimatedCredits: 15,
  },
  {
    name: 'crawlerlane_export_markdown',
    description: 'Export a CrawlerLane report as markdown.',
    inputSchema: crawlerlaneExportMarkdownSchema,
    route: '/v1/crawlerlane/export/markdown',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.export.markdown',
    estimatedCredits: 5,
  },
  {
    name: 'crawlerlane_export_json',
    description: 'Export a CrawlerLane report as JSON.',
    inputSchema: crawlerlaneExportJsonSchema,
    route: '/v1/crawlerlane/export/json',
    method: 'POST',
    product: 'crawlerlane',
    action: 'crawlerlane.export.json',
    estimatedCredits: 5,
  },
]

export const TOOL_MAP = new Map(ALL_TOOLS.map((t) => [t.name, t]))
export const TOOL_NAMES = ALL_TOOLS.map((t) => t.name)
